[project]
name = "advent-of-code"
version = "0.1.0"
description = "Collection of all Advent of Code solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
    "regex>=2025.9.18",
]
