import operator
from functools import reduce
from pathlib import Path


def part1(puzzle: str) -> int:
    count = 0

    problems = [problem.split() for problem in puzzle.splitlines()]

    for i in range(0, len(problems[0])):
        values = [int(problems[r][i]) for r in range(len(problems) - 1)]

        match problems[-1][i]:
            case '+':
                value = sum(values)
            case '*':
                value = reduce(operator.mul, values, 1)

        count += value
    return count

# Generated by GPT-5.1
def part2(puzzle: str) -> int:
    count = 0

    rows = puzzle.splitlines()
    width = max(len(r) for r in rows)
    rows = [r.ljust(width) for r in rows]

    col = width - 1

    while col >= 0:
        # Skip separator columns
        if all(rows[r][col] == " " for r in range(len(rows))):
            col -= 1
            continue

        # Collect columns belonging to this problem
        problem_cols = []
        while col >= 0 and not all(rows[r][col] == " " for r in range(len(rows))):
            problem_cols.append(col)
            col -= 1

        # Operator is at the bottom of the rightmost column
        op = next(
            rows[-1][c]
            for c in problem_cols
            if rows[-1][c] in "+*"
        )

        values = []
        for c in problem_cols:
            digits = [
                rows[r][c]
                for r in range(len(rows) - 1)
                if rows[r][c].isdigit()
            ]
            if digits:
                values.append(int("".join(digits)))

        match op:
            case '+':
                value = sum(values)
            case '*':
                value = reduce(operator.mul, values, 1)

        count += value

    return count

if __name__ == "__main__":
    puzzle = (Path(__file__).parent / "input.txt").read_text()

    print(f"Part 1: {part1(puzzle)}")
    print(f"Part 2: {part2(puzzle)}")